### ISSUE TITLE
No payapl button in safari

### ISSUE THREAD

**Issue by mycetome** [shopware5/SwagPaymentPayPalUnified#41] opened 2023-12-18 17:58 UTC
https://github.com/shopware5/SwagPaymentPayPalUnified/blob/11feabf5c1adaaadb2db89507055d9b73a26a5aa/Resources/views/frontend/_public/src/js/jquery.swag-paypal-unified.in-context-checkout.js#L81

Safari occasionally loads the PayPal javascript from browser cache. In these cases, no success function is called and the confirmation page does not have a buy button. 

This may also be an issue with smart payment buttons, but we haven't tested this.

This createButton replacement solves this problem, but it is not the most elegant solution. A fallback button should also be implemented, as recommended by Paypal. 

createButton: function() {
            var me = this,
                $head = $('head'),
                mycLoadingError = 'AjaxErrorClassName',
                mycAjaxComplete = 'AjaxCompleteClassName',
                mycppAjaxCached = 'AjaxCachedClassName';

            if (!$head.hasClass(this.opts.paypalScriptLoadedSelector)) {
                $.ajax({
                    url: this.renderSdkUrl(),
                    dataType: 'script',
                    cache: true,
                    success: function() {
                        $head.addClass(me.opts.paypalScriptLoadedSelector);
                        me.paypal = window.paypal;
                        me.renderButton();
                    },
                    error: function() {
                        $head.addClass(mycLoadingError);
                    },
                    complete: function() {
                        $head.addClass(mycAjaxComplete);
                    }
                });
                if ( (!$head.hasClass(this.opts.paypalScriptLoadedSelector)) && (window.paypal) && (!$head.hasClass(mycLoadingError))  && (!$head.hasClass(mycAjaxComplete))) {
                    // no error, no success, no complete (no ajax request at all),   paypal exists => window.paypal loaded from memory 
                   //  render paypal button
                    $head.addClass(mycppAjaxCached); // internal logging
                    me.paypal = window.paypal;
                    me.renderButton();
               
                }
                else if ($head.hasClass(mycLoadingError)) {
                    // errorhandling, push GTM dataLayer event
                    
                }; 

            } else {
                this.paypal = window.paypal;
                this.renderButton();
            }
        },

**Comment by mitelg** [comment] 2023-12-28 07:44
hey @mycetome 
thanks for bringing this up. due to the holiday season we need some time to have a closer look at it. We will get back to you.

**Comment by swDennis** [comment] 2024-01-19 09:22
Hello @mycetome, 

can you reproduce this issue? I have a possible solution. It is possible that you can check that?

**Comment by reppaMarc** [comment] 2024-01-19 11:02
@swDennis checked fix on our test instance -> works!

**Comment by swDennis** [comment] 2024-01-19 11:30
:+1: Thank you, then I have to adjust all other buttons, and then I can release it!

**Comment by mitelg** [comment] 2024-01-22 10:30
Fixed with https://github.com/shopware5/SwagPaymentPayPalUnified/pull/43

**Closed by mitelg** 2024-01-22 10:30 UTC
